# Generated by Django 5.0.6 on 2024-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, help_text='slug', max_length=100, null=True, verbose_name='slug')),
                ('content', models.TextField(help_text='Введите текст статьи', verbose_name='Содержание')),
                ('preview', models.ImageField(blank=True, help_text='Загрузить превью статьи', null=True, upload_to='preview/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published', models.BooleanField(default=True, help_text='Укажите признак публикации статьи', verbose_name='Признак публикации')),
                ('number_views', models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров статьи', verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('title',),
            },
        ),
    ]
