# Generated by Django 4.2.2 on 2024-07-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('title',), 'permissions': [('can_manage_publications', 'can manage publications')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
