# Generated by Django 5.0.6 on 2024-07-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_version', models.PositiveIntegerField(help_text='Укажите номер версии', verbose_name='Номер версии')),
                ('name', models.CharField(help_text='Укажите название версии', max_length=100, verbose_name='Название версии')),
                ('current_version', models.BooleanField(verbose_name='Признак текущей версии')),
                ('product', models.ForeignKey(help_text='Название продукта', on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ('number_version', 'name'),
            },
        ),
    ]
