# Generated by Django 4.2.2 on 2024-07-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_in_stock_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('can_unpublish_a_product', 'can unpublish a product'), ('can_change_description_product', 'can change description product'), ('can_change_category_product', 'can change category product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
