# Generated by Django 4.2.2 on 2024-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Укажите признак публикации', verbose_name='Признак публикации'),
        ),
    ]
