# Generated by Django 4.2.2 on 2024-07-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('can_change_is_published', 'can change is published'), ('can_change_description_product', 'can change description product'), ('can_change_category_product', 'can change category product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
